ServerEvents.recipes(event => {

event.remove({ output: "modern_industrialization:quantum_helmet" })
event.remove({ output: "modern_industrialization:quantum_chestplate" })
event.remove({ output: "modern_industrialization:quantum_leggings" })
event.remove({ output: "modern_industrialization:quantum_boots" })
event.remove({ output: "hostile_neural_industrialization:large_loot_fabricator" })
event.remove({ output: "hostile_neural_industrialization:large_simulation_chamber" })
event.remove({ output: "hostile_neural_industrialization:prediction_machine_casing" })
event.remove({ output: "mi_tweaks:flux_transformer" })
event.remove({ output: 'modern_industrialization:op_amp' })
event.remove([{ input: 'modern_industrialization:raw_titanium', output: 'modern_industrialization:titanium_hot_ingot' }])
event.remove([{ input: '#c:dusts/bauxite', output: 'modern_industrialization:titanium_tiny_dust' }])
event.remove({output: 'industrialization_overdrive:multi_processing_array'})
event.remove({output: 'industrialization_overdrive:pyrolyse_oven'})
event.remove({output: 'modern_industrialization:magnetite_dust'})
event.remove({output: 'modern_industrialization:magnalium_ingot'})
event.remove({output: 'modern_industrialization:replicator'})
//видалення руди
event.remove({output: 'modern_industrialization:raw_lead'})
event.remove({output: 'modern_industrialization:salt_crushed_dust'})
event.remove({output: 'modern_industrialization:bauxite_crushed_dust'})
event.remove({output: 'minecraft:raw_gold'})
event.remove({output: 'modern_industrialization:emerald_crushed_dust'})
event.remove({output: 'modern_industrialization:redstone_crushed_dust'})
event.remove({output: 'modern_industrialization:monazite_crushed_dust'})
event.remove([{ input: 'modern_industrialization:electrum_dust', output: 'modern_industrialization:electrum_ingot' }])
event.remove([{ input: 'modern_industrialization:silver_block', output: 'modern_industrialization:electrum_block' }])

event.remove([{ input: '#c:dusts/salt', output: 'modern_industrialization:sodium_dust' }])

event.remove({output: 'modern_industrialization:processing_unit_board'})
event.remove({output: 'modern_industrialization:stainless_steel_hot_ingot'})
event.remove({output: 'modern_industrialization:tungsten_cable'})
event.remove({output: 'modern_industrialization:electric_quarry'})
event.remove({output: 'modern_industrialization:steam_quarry'})

event.remove({ type: 'modern_industrialization:quarry' })

event.remove([{ input: 'modern_industrialization:osmiridium_dust', output: 'modern_industrialization:osmiridium_ingot' }])
event.remove([{ input: 'modern_industrialization:titanium_64_dust', output: 'modern_industrialization:titanium_64_ingot' }])
event.remove([{ input: 'modern_industrialization:rhodium_dust', output: 'modern_industrialization:rhodium_ingot' }])
event.remove([{ input: 'modern_industrialization:rhodium_plated_palladium_dust', output:'modern_industrialization:rhodium_plated_palladium_ingot' }])
event.remove([{ input: 'modern_industrialization:niobium_titanium_alloy_dust', output: 'modern_industrialization:niobium_titanium_alloy_ingot' }])
event.remove([{ input: 'modern_industrialization:incoloy_dust', output: 'modern_industrialization:incoloy_ingot' }])
event.remove([{ input: 'modern_industrialization:chrome_vanadium_steel_dust', output: 'modern_industrialization:chrome_vanadium_steel_ingot' }])
  
})