ServerEvents.recipes(event => {
    event.remove({ type: "railcraft:crusher" });
    event.remove({ type: "railcraft:blast_furnace" });
    event.remove({ type: "railcraft:coke_oven" });

    const itemsToRemove = [
        'railcraft:nickel_iron_battery',
        'railcraft:zinc_silver_battery_empty',
        'railcraft:steel_ingot',
        'railcraft:steel_block',
        'railcraft:zinc_silver_battery',
        'railcraft:nickel_zinc_battery',
        'railcraft:blast_furnace_bricks',
        'railcraft:low_pressure_steam_boiler_tank',
        'railcraft:fluid_fueled_firebox',
        'railcraft:coke_oven_bricks',
        'railcraft:crusher',
        'railcraft:steam_oven',
        'railcraft:steam_locomotive',
        'railcraft:zinc_carbon_battery_empty',
        'railcraft:locomotive_detector',
        'railcraft:water_tank_siding',
        'railcraft:solid_fueled_firebox',
        'railcraft:high_pressure_steam_boiler_tank',
        'railcraft:zinc_carbon_battery',
        'railcraft:tunnel_bore',
        'railcraft:world_spike',
        'railcraft:personal_world_spike',
        'railcraft:steam_turbine',
        'railcraft:white_iron_tank_wall',
        'railcraft:white_steel_tank_wall',
        'railcraft:brass_ingot',
        'railcraft:bronze_ingot',
        'railcraft:invar_ingot',
        'railcraft:powered_rolling_machine',
        'railcraft:steel_sword',
        'railcraft:steel_pickaxe',
        'railcraft:steel_axe',
        'railcraft:steel_shovel',
        'railcraft:steel_hoe',
        'railcraft:steel_helmet',
        'railcraft:steel_chestplate',
        'railcraft:steel_leggings',
        'railcraft:steel_boots',
        'railcraft:lead_plate',
        'railcraft:invar_plate',
        'railcraft:steel_plate',
        'railcraft:bronze_plate',
        'railcraft:silver_plate',
        'railcraft:nickel_plate',
        'railcraft:iron_plate',
        'railcraft:copper_plate',
        'railcraft:gold_plate',
        'railcraft:tin_plate',
        'railcraft:zinc_plate',
        'railcraft:brass_plate',
        'railcraft:lead_gear',
        'railcraft:invar_gear',
        'railcraft:steel_gear',
        'railcraft:bronze_gear',
        'railcraft:silver_gear',
        'railcraft:nickel_gear',
        'railcraft:iron_gear',
        'railcraft:copper_gear',
        'railcraft:gold_gear',
        'railcraft:standard_rail',
        'railcraft:black_post',
        'railcraft:rebar',
        'railcraft:wooden_tie',
        'railcraft:stone_tie',
        'minecraft:powered_rail',
        'minecraft:detector_rail',
        'minecraft:activator_rail'
    ];

    itemsToRemove.forEach(item => {
        event.remove({ output: item });
    });
});
