ServerEvents.recipes(event => {
    event.remove({output: "toms_storage:paint_kit"})
    event.remove({output: 'toms_storage:adv_wireless_terminal'})
    event.remove({output: 'toms_storage:wireless_terminal'})
    event.remove({output: 'toms_storage:polymorphic_item_filter'})
    event.remove({output: 'toms_storage:tag_item_filter'})
    event.remove({output: 'toms_storage:item_filter'})
    event.remove({output: 'toms_storage:level_emitter'})
    event.remove({output: 'toms_storage:basic_inventory_hopper'})
    event.remove({ output: "travelanchors:travel_staff" })
    event.remove({ output: "travelanchors:travel_anchor" })
    event.remove({ output: "toms_storage:storage_terminal" })
    event.remove({ output: "toms_storage:crafting_terminal" })
    event.remove({ output: "toms_storage:trim" })
    event.remove({ output: "toms_storage:inventory_cable" })
    event.remove({ output: "toms_storage:inventory_interface" })
    event.remove({ output: "toms_storage:inventory_cable_connector" })
    event.remove({ output: "toms_storage:inventory_proxy" })
    event.remove({ output: "toms_storage:inventory_interface" })
    event.remove({ output: "toms_storage:inventory_connector" })
})
