ServerEvents.recipes(event => {

  event.recipes.modern_industrialization.circuit_assembler(4, 100)
  .itemIn("1x modern_industrialization:silicon_wafer")
  .itemIn("2x #ae2:all_certus_quartz")
  .itemIn("1x modern_industrialization:analog_circuit")
  .itemIn("1x ae2:logic_processor")
  .fluidIn("modern_industrialization:molten_redstone", 200)
  .itemOut("1x ae2:cell_component_1k")

  event.recipes.modern_industrialization.circuit_assembler(4, 100)
  .itemIn("2x modern_industrialization:gold_fine_wire")
  .itemIn("3x ae2:cell_component_1k")
  .itemIn("3x modern_industrialization:analog_circuit")
  .itemIn("1x ae2:calculation_processor")
  .fluidIn("modern_industrialization:molten_redstone", 100)
  .itemOut("1x ae2:cell_component_4k")

  event.recipes.modern_industrialization.circuit_assembler(4, 100)
  .itemIn("4x modern_industrialization:gold_fine_wire")
  .itemIn("3x ae2:cell_component_4k")
  .itemIn("1x modern_industrialization:electronic_circuit")
  .itemIn("1x ae2:calculation_processor")
  .fluidIn("modern_industrialization:molten_redstone", 100)
  .fluidIn("modern_industrialization:molten_glowstone", 250)
  .itemOut("1x ae2:cell_component_16k")

  event.recipes.modern_industrialization.circuit_assembler(4, 100)
  .itemIn("8x modern_industrialization:gold_fine_wire")
  .itemIn("3x ae2:cell_component_16k")
  .itemIn("3x modern_industrialization:electronic_circuit")
  .itemIn("1x ae2:calculation_processor")
  .fluidIn("modern_industrialization:molten_redstone", 200)
  .fluidIn("modern_industrialization:molten_glowstone", 500)
  .itemOut("1x ae2:cell_component_64k")

  event.recipes.modern_industrialization.circuit_assembler(4, 100)
  .itemIn("16x modern_industrialization:gold_fine_wire")
  .itemIn("3x ae2:cell_component_64k")
  .itemIn("1x modern_industrialization:digital_circuit")
  .itemIn("1x ae2:calculation_processor")
  .fluidIn("modern_industrialization:molten_redstone", 100)
  .fluidIn("modern_industrialization:molten_glowstone", 250)
  .itemOut("1x ae2:cell_component_256k")

  event.recipes.modern_industrialization.circuit_assembler(4, 800)
  .itemIn("8x megacells:mega_energy_cell")
  .itemIn("1x modern_industrialization:singularity")
  .itemOut("1x ae2:creative_energy_cell", 0.01)

  // MEGA Cells
  event.recipes.modern_industrialization.circuit_assembler(4, 100)
  .itemIn("4x modern_industrialization:niobium_titanium_alloy_fine_wire")
  .itemIn("3x ae2:cell_component_256k")
  .itemIn("3x modern_industrialization:digital_circuit")
  .itemIn("1x megacells:accumulation_processor")
  .fluidIn("modern_industrialization:cryofluid", 100)
  .itemOut("1x megacells:cell_component_1m")

  event.recipes.modern_industrialization.circuit_assembler(4, 100)
  .itemIn("8x modern_industrialization:niobium_titanium_alloy_fine_wire")
  .itemIn("4x megacells:cell_component_1m")
  .itemIn("1x modern_industrialization:processing_unit")
  .itemIn("1x megacells:accumulation_processor")
  .fluidIn("modern_industrialization:cryofluid", 250)
  .itemOut("1x megacells:cell_component_4m")

  event.recipes.modern_industrialization.circuit_assembler(4, 100)
  .itemIn("16x modern_industrialization:niobium_titanium_alloy_fine_wire")
  .itemIn("4x megacells:cell_component_4m")
  .itemIn("3x modern_industrialization:processing_unit")
  .itemIn("1x megacells:accumulation_processor")
  .fluidIn("modern_industrialization:cryofluid", 500)
  .itemOut("1x megacells:cell_component_16m")

  event.recipes.modern_industrialization.circuit_assembler(4, 100)
  .itemIn("32x modern_industrialization:niobium_titanium_alloy_fine_wire")
  .itemIn("4x megacells:cell_component_16m")
  .itemIn("1x modern_industrialization:quantum_circuit")
  .itemIn("1x megacells:accumulation_processor")
  .fluidIn("modern_industrialization:cryofluid", 1000)
  .itemOut("1x megacells:cell_component_64m")

  event.recipes.modern_industrialization.circuit_assembler(4, 100)
  .itemIn("64x modern_industrialization:niobium_titanium_alloy_fine_wire")
  .itemIn("4x megacells:cell_component_64m")
  .itemIn("3x modern_industrialization:quantum_circuit")
  .itemIn("1x megacells:accumulation_processor")
  .fluidIn("modern_industrialization:cryofluid", 2000)
  .itemOut("1x megacells:cell_component_256m")

  event.recipes.modern_industrialization.circuit_assembler(4, 100)
  .itemIn("8x modern_industrialization:annealed_copper_cable")
  .itemIn("4x modern_industrialization:cadmium_battery")
  .itemIn("4x modern_industrialization:platinum_plate")
  .itemIn("1x roll_mod:fr4_sheet")
  .fluidIn("modern_industrialization:polyvinyl_chloride", 250)
  .itemOut("1x modern_industrialization:processing_unit_board")

    event.recipes.modern_industrialization.circuit_assembler(32, 100)
  .itemIn("6x modern_industrialization:rhodium_fine_wire")
  .itemIn("6x modern_industrialization:redstone_alloy_fine_wire")
  .itemIn("4x extendedae:concurrent_processor_print")
  .itemIn("4x ae2:printed_silicon")
  .itemIn("1x modern_industrialization:digital_circuit")
  .itemOut("1x extendedae:concurrent_processor")

    event.recipes.modern_industrialization.circuit_assembler(32, 100)
  .itemIn("64x modern_industrialization:palladium_fine_wire")
  .itemIn("6x modern_industrialization:niobium_titanium_alloy_plate")
  .itemIn("6x #ae2:smart_dense_cable")
  .itemIn("4x ae2:engineering_processor")
  .itemIn("4x ae2:logic_processor")
  .itemIn("1x modern_industrialization:processing_unit")
  .fluidIn("modern_industrialization:cryofluid", 200)
  .itemOut("1x ae2:quantum_ring")

event.recipes.modern_industrialization.circuit_assembler(128, 200)
.itemIn("2x modern_industrialization:digital_circuit")
.itemIn("2x modern_industrialization:kanthal_cable")
.itemIn("1x roll_mod:lapotron_large_crystal")
.fluidIn("200x modern_industrialization:molten_energium")
.itemOut("1x roll_mod:lapotron_battery_t1")

event.recipes.modern_industrialization.circuit_assembler(128, 600)
.itemIn("25x roll_mod:lapotron_lens")
.itemIn("16x modern_industrialization:platinum_cable")
.itemIn("16x modern_industrialization:netherite_plate")
.itemIn("4x modern_industrialization:processing_unit")
.itemIn("4x modern_industrialization:turbo_upgrade")
.itemIn("1x modern_industrialization:large_heat_exchanger")
.fluidIn("200x modern_industrialization:cryofluid")
.itemOut("1x roll_mod:lapotron_battery_t2")

event.recipes.modern_industrialization.circuit_assembler(128, 600)
.itemIn("1x roll_mod:lapotron_battery_t2")
.itemIn("64x roll_mod:lapotron_lens")
.itemIn("16x modern_industrialization:osmiridium_plate")
.itemIn("16x roll_mod:nether_star_plate")
.itemIn("8x modern_industrialization:processing_unit")
.itemIn("32x roll_mod:standard_chip_pmic")
.fluidIn("200x modern_industrialization:cryofluid")
.itemOut("1x roll_mod:lapotron_battery_t3")
  
event.recipes.modern_industrialization.circuit_assembler(64, 100)
.itemIn("6x modern_industrialization:ruthenium_plate")
.itemIn("4x ae2:quartz_glass")
.itemIn("1x modern_industrialization:digital_circuit")
.fluidIn("200x modern_industrialization:polytetrafluoroethylene")
.itemOut("1x megacells:mega_item_cell_housing")

event.recipes.modern_industrialization.circuit_assembler(64, 100)
.itemIn("12x modern_industrialization:ruthenium_plate")
.itemIn("4x ae2:quartz_glass")
.itemIn("1x modern_industrialization:digital_circuit")
.fluidIn("200x modern_industrialization:epoxy")
.itemOut("4x megacells:mega_item_cell_housing")

event.recipes.modern_industrialization.circuit_assembler(64, 100)
.itemIn("6x modern_industrialization:platinum_plate")
.itemIn("4x ae2:quartz_glass")
.itemIn("1x modern_industrialization:digital_circuit")
.fluidIn("200x modern_industrialization:polytetrafluoroethylene")
.itemOut("1x megacells:mega_fluid_cell_housing")

event.recipes.modern_industrialization.circuit_assembler(64, 100)
.itemIn("12x modern_industrialization:platinum_plate")
.itemIn("4x ae2:quartz_glass")
.itemIn("1x modern_industrialization:digital_circuit")
.fluidIn("200x modern_industrialization:epoxy")
.itemOut("4x megacells:mega_fluid_cell_housing")

event.recipes.modern_industrialization.circuit_assembler(64, 800)
.itemIn("12x ae2:quartz_glass")
.itemIn("6x roll_mod:nether_star_plate")
.itemIn("6x ae2:fluix_smart_cable")
.itemIn("6x modern_industrialization:niobium_titanium_alloy_fine_wire")
.itemIn("6x ae2:engineering_processor")
.itemOut("1x ae2:quantum_link")

event.recipes.modern_industrialization.circuit_assembler(24, 100)
.itemIn("24x ae2:fluix_pearl")
.itemIn("12x modern_industrialization:niobium_titanium_alloy_fine_wire")
.itemIn("6x modern_industrialization:titanium_64_plate")
.itemIn("6x ae2:fluix_smart_cable")
.itemIn("1x roll_mod:quantum_star")
.itemOut("1x ae2:spatial_pylon")
})