ServerEvents.recipes(event => {
    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn("#c:dusts/redstone", 1)
        .fluidIn("modern_industrialization:creosote", 500)
        .fluidOut("modern_industrialization:lubricant", 500)

    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn("#c:dusts/redstone", 1)
        .fluidIn("modern_industrialization:naphtha", 500)
        .fluidOut("modern_industrialization:lubricant", 500)

    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn("#c:dusts/redstone", 1)
        .fluidIn("modern_industrialization:plant_oil", 500)
        .fluidOut("modern_industrialization:lubricant", 500)

    event.recipes.modern_industrialization.mixer(32, 400)
        .itemIn("#c:honeycombs", 1)
        .itemIn("modern_industrialization:titanium_hot_ingot", 1)
        .itemIn("#c:magma_cream", 1)
        .fluidIn("minecraft:water", 1000)
        .itemOut("4x roll_mod:hot_titanium_gum")

    event.recipes.modern_industrialization.mixer(2, 200)
        .itemIn("#c:dusts/redstone", 1)
        .itemIn("#c:dusts/glowstone", 2)
        .itemIn("#c:gunpowder", 1)
        .itemOut("2x extendedcrafting:luminessence")

    event.recipes.modern_industrialization.mixer(16, 200)
        .itemIn("#c:dusts/redstone", 2)
        .itemIn("#c:slime_balls", 1)
        .itemIn("#createcybernetics:graphene", 2)
        .itemOut("4x createcybernetics:graphene_elastomer")

    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn("roll_mod:clay_dust", 2)
        .itemIn("#c:dusts/brick", 2)
        .itemIn("#c:dusts/bauxite", 2)
        .itemOut("6x modern_industrialization:fire_clay_dust")

    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn("#c:dusts/tin", 1)
        .itemIn("#c:dusts/bismuth", 1)
        .itemOut("2x modern_industrialization:soldering_alloy_dust")

    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn("#c:dusts/tin", 1)
        .itemIn("#c:dusts/silver", 1)
        .itemOut("2x modern_industrialization:soldering_alloy_dust")

    event.recipes.modern_industrialization.mixer(8, 100)
        .itemIn("#c:dusts/iridium", 3)
        .itemIn("#c:dusts/osmium", 1)
        .itemOut("4x modern_industrialization:osmiridium_dust")

    event.recipes.modern_industrialization.mixer(8, 100)
        .itemIn("#c:dusts/iron", 4)
        .itemIn("#c:dusts/chromium", 1)
        .itemIn("#c:dusts/aluminum", 4)
        .itemOut("4x modern_industrialization:kanthal_dust")

    event.recipes.modern_industrialization.mixer(16, 200)
        .itemIn("#c:dusts/iron", 7)
        .itemIn("roll_mod:vanadium_dust_clean", 1)
        .itemIn("#c:dusts/chromium", 1)
        .itemIn("#c:dusts/silicon", 3)
        .itemOut("9x modern_industrialization:chrome_vanadium_steel_dust")

    event.recipes.modern_industrialization.mixer(16, 200)
        .itemIn("#c:dusts/titanium", 7)
        .itemIn("#c:dusts/aluminum", 2)
        .itemIn("roll_mod:vanadium_dust_clean", 1)
        .itemOut("10x modern_industrialization:titanium_64_dust")

    event.recipes.modern_industrialization.mixer(8, 100)
        .itemIn("#c:dusts/titanium", 2)
        .itemIn("#c:dusts/niobium", 2)
        .itemOut("4x modern_industrialization:niobium_titanium_alloy_dust")

    event.recipes.modern_industrialization.mixer(8, 100)
        .itemIn("#c:dusts/iridium", 3)
        .itemIn("#c:dusts/osmium", 1)
        .itemOut("4x modern_industrialization:osmiridium_dust")

    event.recipes.modern_industrialization.mixer(16, 200)
        .itemIn("#c:dusts/iron", 6)
        .itemIn("#c:dusts/chromium", 4)
        .itemIn("#c:dusts/titanium", 2)
        .itemIn("#c:dusts/yttrium", 2)
        .itemOut("14x modern_industrialization:incoloy_dust")

    event.recipes.modern_industrialization.mixer(32, 400)
        .fluidIn("modern_industrialization:dimethylhydrazine", 1000)
        .fluidIn("modern_industrialization:dinitrogen_tetroxide", 1000)
        .fluidOut("modern_industrialization:rocket_propellant", 2000)

    event.recipes.modern_industrialization.mixer(24, 100)
        .fluidIn("modern_industrialization:distilled_water", 10000)
        .itemIn("roll_mod:1_circuit", 1, 0.0)
        .itemIn("#c:dusts/salt", 1)
        .fluidOut("modern_industrialization:saline_solution", 10000)

    event.recipes.modern_industrialization.mixer(24, 300)
        .fluidIn("minecraft:water", 4000)
        .fluidIn("modern_industrialization:sodium_hydroxide", 250)
        .itemIn("#c:kelp", 64)
        .fluidOut("modern_industrialization:diluted_agar_solution", 250)

    event.recipes.modern_industrialization.mixer(24, 300)
        .fluidIn("modern_industrialization:distilled_water", 2000)
        .itemIn("roll_mod:agar_dust", 10)
        .itemIn("roll_mod:calcium_dust", 6)
        .itemIn("#c:dusts/salt", 4)
        .fluidOut("modern_industrialization:raw_nutrient_solution", 2000)

    event.recipes.modern_industrialization.mixer(24, 300)
        .itemIn("#c:magma_cream", 32)
        .itemIn("roll_mod:sulfur_jam", 2)
        .itemIn("roll_mod:sulfur_berry_pie", 2)
        .itemIn("roll_mod:syringe", 1)
        .fluidIn("modern_industrialization:sulfuric_acid", 2000)
        .itemOut("1x roll_mod:injection_fire_resistance")

    event.recipes.modern_industrialization.mixer(24, 300)
        .itemIn("#c:obsidian", 4)
        .itemIn("roll_mod:syringe", 1)
        .fluidIn("modern_industrialization:adrenaline", 1000)
        .itemOut("1x roll_mod:injection_resistance")

    event.recipes.modern_industrialization.mixer(24, 300)
        .itemIn("#c:sugar", 8)
        .itemIn("roll_mod:syringe", 1)
        .fluidIn("modern_industrialization:adrenaline", 1000)
        .itemOut("1x roll_mod:injection_haste")

    event.recipes.modern_industrialization.mixer(24, 300)
        .itemIn("roll_mod:sulfur_berry", 8)
        .itemIn("#c:black_wool", 3)
        .itemIn("#c:red_wool", 3)
        .itemIn("roll_mod:syringe", 1)
        .fluidIn("modern_industrialization:lubricant", 2000)
        .itemOut("1x roll_mod:injection_resistance")

    event.recipes.modern_industrialization.mixer(24, 300)
        .itemIn("#c:cactus", 1)
        .itemIn("#c:rings/gold", 16)
        .itemIn("roll_mod:syringe", 1)
        .fluidIn("modern_industrialization:adrenaline", 1000)
        .itemOut("1x roll_mod:injection_speed")

    event.recipes.modern_industrialization.mixer(24, 300)
        .itemIn("#c:ghast_tears", 1)
        .itemIn("roll_mod:syringe", 1)
        .fluidIn("modern_industrialization:adrenaline", 1000)
        .itemOut("1x roll_mod:injection_regen")

    event.recipes.modern_industrialization.mixer(24, 300)
        .itemIn("roll_mod:sulfur_berry", 8)
        .itemIn("#c:magma_cream", 1)
        .itemIn("#c:dusts/sulfur", 4)
        .itemIn("roll_mod:syringe", 1)
        .fluidIn("modern_industrialization:adrenaline", 1000)
        .itemOut("1x roll_mod:injection_fire_resistance")

    event.recipes.modern_industrialization.mixer(64, 200)
        .itemIn("#c:dusts/redstone", 8)
        .itemIn("#c:dusts/diamond", 4)
        .itemIn("#c:dusts/silicon", 4)
        .itemOut("16x roll_mod:energium_dust")

    event.recipes.modern_industrialization.mixer(64, 200)
        .itemIn("#c:dusts/ruby", 16)
        .itemIn("#c:dusts/diamond", 4)
        .itemIn("#c:dusts/silicon", 4)
        .itemOut("16x roll_mod:energium_dust")

    event.recipes.modern_industrialization.mixer(4, 100)
        .itemIn("#c:dusts/steel", 5)
        .itemIn("#c:dusts/nickel", 3)
        .itemIn("#c:dusts/gold", 1)
        .itemIn("#c:dusts/silver", 1)
        .itemOut("10x modern_industrialization:black_steel_dust")

    event.recipes.modern_industrialization.mixer(32, 600)
        .fluidIn("modern_industrialization:nitric_acid", 1000)
        .fluidIn("modern_industrialization:hydrochloric_acid", 2000)
        .fluidOut("modern_industrialization:aqua_regia", 3000)

    event.recipes.modern_industrialization.mixer(8, 100)
        .itemIn("#c:dusts/palladium", 3)
        .itemIn("#c:dusts/rhodium", 2)
        .itemOut("5x modern_industrialization:rhodium_plated_palladium_dust")

    event.recipes.modern_industrialization.mixer(2, 200)
        .itemIn("roll_mod:raw_latex", 1)
        .itemIn("#c:dusts/coal", 3)
        .itemOut("2x roll_mod:raw_rubber")

    event.recipes.modern_industrialization.mixer(16, 200)
        .itemIn("#c:dusts/aluminum", 4)
        .itemIn("#c:dusts/magnesium", 1)
        .itemOut("5x modern_industrialization:magnalium_dust")

    event.recipes.modern_industrialization.mixer(2, 300)
        .itemIn("#c:logs", 1)
        .fluidIn("modern_industrialization:creosote", 4000)
        .itemOut("1x roll_mod:treated_log")

    event.recipes.modern_industrialization.mixer(24, 100)
        .fluidIn("minecraft:water", 10000)
        .fluidIn("modern_industrialization:nitrogen", 1000)
        .itemIn("roll_mod:potassium_dust", 1)
        .itemIn("#c:dusts/phosphorus", 1)
        .fluidOut("extended_industrialization:npk_fertilizer", 16000)

    event.recipes.modern_industrialization.mixer(24, 100)
        .itemIn("ae2:ender_dust", 8)
        .itemIn("#c:dusts/lead", 4)
        .itemIn("#c:dusts/tin", 1)
        .itemIn("#c:dusts/platinum", 1)
        .itemOut("4x modern_industrialization:enderium_dust")

    event.recipes.modern_industrialization.mixer(4, 200)
        .itemIn("#c:dusts/saltpeter", 2)
        .itemIn("#c:dusts/sulfur", 3)
        .itemOut("5x roll_mod:sulfur_saltpeter_mixture")

    event.recipes.modern_industrialization.mixer(4, 100)
        .itemIn("#c:dusts/copper", 5)
        .itemIn("#c:dusts/silver", 2)
        .itemIn("#c:dusts/gold", 2)
        .itemOut("9x modern_industrialization:black_bronze_dust")

    event.recipes.modern_industrialization.mixer(4, 100)
        .itemIn("#c:dusts/copper", 4)
        .itemIn("#c:dusts/zinc", 3)
        .itemIn("#c:dusts/bismuth", 2)
        .itemOut("9x modern_industrialization:bismuth_bronze_dust")
})
