ServerEvents.recipes(event => {
    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn("#c:dusts/redstone", 1)
        .fluidIn("modern_industrialization:creosote", 500)
        .fluidOut("modern_industrialization:lubricant", 500)

    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn("#c:dusts/redstone", 1)
        .fluidIn("modern_industrialization:naphtha", 500)
        .fluidOut("modern_industrialization:lubricant", 500)

    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn("#c:dusts/redstone", 1)
        .fluidIn("modern_industrialization:plant_oil", 500)
        .fluidOut("modern_industrialization:lubricant", 500)

    event.recipes.modern_industrialization.mixer(32, 400)
        .itemIn("1x #c:honeycombs")
        .itemIn("1x modern_industrialization:titanium_hot_ingot")
        .itemIn("1x #c:magma_cream")
        .fluidIn("minecraft:water", 1000)
        .itemOut("4x roll_mod:hot_titanium_gum")

    event.recipes.modern_industrialization.mixer(2, 200)
        .itemIn("1x #c:dusts/redstone")
        .itemIn("2x #c:dusts/glowstone")
        .itemIn("1x #c:gunpowder")
        .itemOut("2x extendedcrafting:luminessence")

    event.recipes.modern_industrialization.mixer(16, 200)
        .itemIn("2x #c:dusts/redstone")
        .itemIn("1x #c:slime_balls")
        .itemIn("2x #createcybernetics:graphene")
        .itemOut("4x createcybernetics:graphene_elastomer")

    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn("2x roll_mod:clay_dust")
        .itemIn("2x #c:dusts/brick")
        .itemIn("2x #c:dusts/bauxite")
        .itemOut("6x #c:dusts/fire_clay")

    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn("1x #c:dusts/tin")
        .itemIn("1x #c:dusts/bismuth")
        .itemOut("2x #c:dusts/soldering_alloy")

    event.recipes.modern_industrialization.mixer(2, 100)
        .itemIn("1x #c:dusts/tin")
        .itemIn("1x #c:dusts/silver")
        .itemOut("2x #c:dusts/soldering_alloy")

    event.recipes.modern_industrialization.mixer(8, 100)
        .itemIn("3x #c:dusts/iridium")
        .itemIn("1x #c:dusts/osmium")
        .itemOut("4x #c:dusts/osmiridium")

    event.recipes.modern_industrialization.mixer(8, 100)
        .itemIn("4x #c:dusts/iron")
        .itemIn("1x #c:dusts/chromium")
        .itemIn("4x #c:dusts/aluminum")
        .itemOut("4x #c:dusts/kanthal")

    event.recipes.modern_industrialization.mixer(16, 200)
        .itemIn("7x #c:dusts/iron")
        .itemIn("1x roll_mod:vanadium_dust_clean")
        .itemIn("1x #c:dusts/chromium")
        .itemIn("3x #c:dusts/silicon")
        .itemOut("9x #c:dusts/chrome_vanadium_steel")

    event.recipes.modern_industrialization.mixer(16, 200)
        .itemIn("7x #c:dusts/titanium")
        .itemIn("2x #c:dusts/aluminum")
        .itemIn("1x roll_mod:vanadium_dust_clean")
        .itemOut("10x #c:dusts/titanium_64")

    event.recipes.modern_industrialization.mixer(8, 100)
        .itemIn("2x #c:dusts/titanium")
        .itemIn("2x #c:dusts/niobium")
        .itemOut("4x #c:dusts/niobium_titanium_alloy")

    event.recipes.modern_industrialization.mixer(8, 100)
        .itemIn("3x #c:dusts/iridium")
        .itemIn("1x #c:dusts/osmium")
        .itemOut("4x #c:dusts/osmiridium")

    event.recipes.modern_industrialization.mixer(16, 200)
        .itemIn("6x #c:dusts/iron")
        .itemIn("4x #c:dusts/chromium")
        .itemIn("2x #c:dusts/titanium")
        .itemIn("2x #c:dusts/yttrium")
        .itemOut("14x #c:dusts/incoloy")

    event.recipes.modern_industrialization.mixer(32, 400)
        .fluidIn("modern_industrialization:dimethylhydrazine", 1000)
        .fluidIn("modern_industrialization:dinitrogen_tetroxide", 1000)
        .fluidOut("modern_industrialization:rocket_propellant", 2000)

    event.recipes.modern_industrialization.mixer(24, 100)
        .fluidIn("modern_industrialization:distilled_water", 10000)
        .itemIn("1x roll_mod:1_circuit", 0.0)
        .itemIn("1x #c:dusts/salt")
        .fluidOut("modern_industrialization:saline_solution", 10000)

    event.recipes.modern_industrialization.mixer(24, 300)
        .fluidIn("minecraft:water", 4000)
        .fluidIn("modern_industrialization:sodium_hydroxide", 250)
        .itemIn("64x #c:kelp")
        .fluidOut("modern_industrialization:diluted_agar_solution", 250)

    event.recipes.modern_industrialization.mixer(24, 300)
        .fluidIn("modern_industrialization:distilled_water", 2000)
        .itemIn("10x roll_mod:agar_dust")
        .itemIn("6x roll_mod:calcium_dust")
        .itemIn("4x #c:dusts/salt")
        .fluidOut("modern_industrialization:raw_nutrient_solution", 2000)

    event.recipes.modern_industrialization.mixer(24, 300)
        .itemIn("32x #c:magma_cream")
        .itemIn("2x roll_mod:sulfur_jam")
        .itemIn("2x roll_mod:sulfur_berry_pie")
        .itemIn("1x roll_mod:syringe")
        .fluidIn("modern_industrialization:sulfuric_acid", 2000)
        .itemOut("1x roll_mod:injection_fire_resistance")

    event.recipes.modern_industrialization.mixer(24, 300)
        .itemIn("4x #c:obsidian")
        .itemIn("1x roll_mod:syringe")
        .fluidIn("modern_industrialization:adrenaline", 1000)
        .itemOut("1x roll_mod:injection_resistance")

    event.recipes.modern_industrialization.mixer(24, 300)
        .itemIn("8x #c:sugar")
        .itemIn("1x roll_mod:syringe")
        .fluidIn("modern_industrialization:adrenaline", 1000)
        .itemOut("1x roll_mod:injection_haste")

    event.recipes.modern_industrialization.mixer(24, 300)
        .itemIn("8x roll_mod:sulfur_berry")
        .itemIn("3x #c:black_wool")
        .itemIn("3x #c:red_wool")
        .itemIn("1x roll_mod:syringe")
        .fluidIn("modern_industrialization:lubricant", 2000)
        .itemOut("1x roll_mod:injection_resistance")

    event.recipes.modern_industrialization.mixer(24, 300)
        .itemIn("1x #c:cactus")
        .itemIn("16x #c:rings/gold")
        .itemIn("1x roll_mod:syringe")
        .fluidIn("modern_industrialization:adrenaline", 1000)
        .itemOut("1x roll_mod:injection_speed")

    event.recipes.modern_industrialization.mixer(24, 300)
        .itemIn("1x #c:ghast_tears")
        .itemIn("1x roll_mod:syringe")
        .fluidIn("modern_industrialization:adrenaline", 1000)
        .itemOut("1x roll_mod:injection_regen")

    event.recipes.modern_industrialization.mixer(24, 300)
        .itemIn("8x roll_mod:sulfur_berry")
        .itemIn("1x #c:magma_cream")
        .itemIn("4x #c:dusts/sulfur")
        .itemIn("1x roll_mod:syringe")
        .fluidIn("modern_industrialization:adrenaline", 1000)
        .itemOut("1x roll_mod:injection_fire_resistance")

    event.recipes.modern_industrialization.mixer(64, 200)
        .itemIn("8x #c:dusts/redstone")
        .itemIn("4x #c:dusts/diamond")
        .itemIn("4x #c:dusts/silicon")
        .itemOut("16x roll_mod:energium_dust")

    event.recipes.modern_industrialization.mixer(64, 200)
        .itemIn("16x #c:dusts/ruby")
        .itemIn("4x #c:dusts/diamond")
        .itemIn("4x #c:dusts/silicon")
        .itemOut("16x roll_mod:energium_dust")

    event.recipes.modern_industrialization.mixer(4, 100)
        .itemIn("5x #c:dusts/steel")
        .itemIn("3x #c:dusts/nickel")
        .itemIn("1x #c:dusts/gold")
        .itemIn("1x #c:dusts/silver")
        .itemOut("10x #c:dusts/black_steel")

    event.recipes.modern_industrialization.mixer(32, 600)
        .fluidIn("modern_industrialization:nitric_acid", 1000)
        .fluidIn("modern_industrialization:hydrochloric_acid", 2000)
        .fluidOut("modern_industrialization:aqua_regia", 3000)

    event.recipes.modern_industrialization.mixer(8, 100)
        .itemIn("3x #c:dusts/palladium")
        .itemIn("2x #c:dusts/rhodium")
        .itemOut("5x #c:dusts/rhodium_plated_palladium")

    event.recipes.modern_industrialization.mixer(2, 200)
        .itemIn("1x roll_mod:raw_latex")
        .itemIn("3x #c:dusts/coal")
        .itemOut("2x roll_mod:raw_rubber")

    event.recipes.modern_industrialization.mixer(16, 200)
        .itemIn("4x #c:dusts/aluminum")
        .itemIn("1x #c:dusts/magnesium")
        .itemOut("5x #c:dusts/magnalium")

    event.recipes.modern_industrialization.mixer(2, 300)
        .itemIn("1x #c:logs")
        .fluidIn("modern_industrialization:creosote", 4000)
        .itemOut("1x roll_mod:treated_log")

    event.recipes.modern_industrialization.mixer(24, 100)
        .fluidIn("10000x minecraft:water")
        .fluidIn("1000x modern_industrialization:nitrogen")
        .itemIn("1x roll_mod:potassium_dust")
        .itemIn("1x #c:dusts/phosphorus")
        .fluidOut("extended_industrialization:npk_fertilizer", 16000)

    event.recipes.modern_industrialization.mixer(24, 100)
        .itemIn("8x ae2:ender_dust")
        .itemIn("4x #c:dusts/lead")
        .itemIn("1x #c:dusts/tin")
        .itemIn("1x #c:dusts/platinum")
        .itemOut("4x #c:dusts/enderium")

    event.recipes.modern_industrialization.mixer(4, 200)
        .itemIn("2x #c:dusts/saltpeter")
        .itemIn("3x #c:dusts/sulfur")
        .itemOut("5x roll_mod:sulfur_saltpeter_mixture")

    event.recipes.modern_industrialization.mixer(4, 100)
        .itemIn("5x #c:dusts/copper")
        .itemIn("2x #c:dusts/silver")
        .itemIn("2x #c:dusts/gold")
        .itemOut("9x #c:dusts/black_bronze")

    event.recipes.modern_industrialization.mixer(4, 100)
        .itemIn("4x #c:dusts/copper")
        .itemIn("3x #c:dusts/zinc")
        .itemIn("2x #c:dusts/bismuth")
        .itemOut("9x #c:dusts/bismuth_bronze")
})
