ServerEvents.recipes(event => {

    const rawBlocks = [
        "roll_mod:raw_scheelite_block",
        "roll_mod:raw_magnetite_block",
        "roll_mod:raw_hematite_block",
        "roll_mod:raw_chalcopyrite_block",
        "roll_mod:raw_galena_block",
        "roll_mod:raw_pyrite_block",
        "roll_mod:raw_cinnabar_block",
        "roll_mod:raw_sphalerite_block",
        "roll_mod:raw_rutile_block",
        "roll_mod:raw_ilmenite_block",
        "roll_mod:raw_chromite_block",
        "roll_mod:raw_malachite_block",
        "roll_mod:raw_bauxite_block",
        "roll_mod:raw_gold_block",
        "roll_mod:raw_silver_block",
        "roll_mod:raw_lead_block",
        "roll_mod:raw_nickel_block",
        "roll_mod:raw_iridium_block",
        "roll_mod:raw_uranium_block",
        "roll_mod:raw_thorium_block",
        "roll_mod:raw_molybdenum_block",
        "roll_mod:raw_tungsten_block",
        "roll_mod:raw_lithium_block",
        "roll_mod:raw_beryllium_block",
        "roll_mod:raw_vanadium_block",
        "roll_mod:raw_titanium_block",
        "roll_mod:raw_osmium_block",
        "roll_mod:raw_bismuth_block",
        "roll_mod:raw_cobalt_block",
        "roll_mod:raw_manganese_block",
        "roll_mod:raw_cassiterite_block",
        "roll_mod:raw_goethite_block",
        "roll_mod:raw_vanadium_magnetite_block",
        "roll_mod:raw_pitchblende_block",
        "roll_mod:raw_uraninite_block",
        "roll_mod:raw_mica_block",
        "roll_mod:raw_yellow_limonite_block",
        "roll_mod:raw_biotite_block",
        "roll_mod:raw_garnierite_block",
        "roll_mod:raw_pentlandite_block",
        "roll_mod:raw_certus_quartz_block",
        "roll_mod:raw_pyrope_block",
        "roll_mod:raw_pyrochlore_block",
        "roll_mod:raw_apatite_block",
        "roll_mod:raw_pyrolusite_block",
        "roll_mod:raw_fluorite_block",
        "roll_mod:raw_peridot_block",
        "roll_mod:raw_sodalite_block",
        "roll_mod:raw_lazurite_block",
        "roll_mod:raw_lapis_lazuli_block",
        "roll_mod:raw_tetrahedrite_block",
        "roll_mod:raw_stibnite_block",
        "roll_mod:raw_blue_topaz_block",
        "roll_mod:raw_topaz_block",
        "roll_mod:raw_chalcocite_block",
        "roll_mod:raw_bornite_block",
        "roll_mod:raw_sulfur_block",
        "roll_mod:raw_monazite_block",
        "roll_mod:raw_ruby_block",
        "roll_mod:raw_redstone_block",
        "roll_mod:raw_saltpeter_block",
        "roll_mod:raw_emerald_block",
        "roll_mod:raw_tantalite_block",
        "roll_mod:raw_molybdenite_block",
        "roll_mod:raw_wulfenite_block",
        "roll_mod:raw_powellite_block",
        "roll_mod:raw_tungstate_block",
        "roll_mod:raw_lepidolite_block",
        "roll_mod:raw_rock_salt_block",
        "roll_mod:raw_salt_block",
        "roll_mod:raw_sheldonite_block",
        "roll_mod:raw_rhodochrosite_block",
        "roll_mod:raw_olivine_block",
        "roll_mod:raw_trona_block",
        "roll_mod:raw_quartz_block",
        "roll_mod:raw_diamond_block",
        "roll_mod:raw_sunnarium_sulfophosphoorthosilicate_block",
        "roll_mod:raw_sunnarium_orthosilicate_block",
        "roll_mod:raw_lignite_coal_block",
        "roll_mod:raw_azure_silver_block",
        "roll_mod:raw_stannite_block",
        "roll_mod:raw_crimson_iron_block",
        "roll_mod:raw_coal_block",
        "roll_mod:raw_borax_block",
        "roll_mod:raw_silver_amalgam_block",
        "roll_mod:raw_gold_amalgam_block",
        "roll_mod:raw_cassiterite_sand_block",
        "roll_mod:raw_bort_block",
        "roll_mod:raw_fluosunnarite_block",
        "roll_mod:raw_rheniite_block",
        "roll_mod:raw_antimony_block"
    ];

    rawBlocks.forEach(block => {
        const dustId = block.replace("_block", "");
        try {
            if (Item.of(block).getId() !== "minecraft:air") {
                event.shapeless(`9x ${dustId}`, [block]);
                event.shaped(block, ['AAA','AAA','AAA'], { A: dustId });
                event.recipes.modern_industrialization.unpacker(2, 100).itemIn(`1x ${block}`).itemOut(`9x ${dustId}`);
                event.recipes.modern_industrialization.packer(2, 100).itemIn(`9x ${dustId}`).itemIn("1x modern_industrialization:packer_block_template", 0.0).itemOut(`1x ${block}`);
            }
        } catch (e) {}
    });

});
