ServerEvents.recipes(event => {
    event.recipes.modern_industrialization.photolithographer(256, 400)
        .itemIn("2x roll_mod:energium_laser", 0.005)
        .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
        .itemIn("1x roll_mod:quartz_lamp", 0.005)
        .itemIn("24x roll_mod:carbon_fiber")
        .itemIn("16x #c:dusts/antimony")
        .itemIn("2x #c:plates/chrome_vanadium_steel")
        .itemIn("24x #c:wires/platinum")
        .itemIn("1x roll_mod:blue_wafer")
        .itemIn("16x #c:dusts/titanium")
        .fluidIn("modern_industrialization:argon", 1000)
        .itemOut("1x roll_mod:blue_wafer_ram")

    event.recipes.modern_industrialization.photolithographer(64, 100)
        .itemIn("1x roll_mod:lapotron_laser", 0.0)
        .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
        .itemIn("1x ae2:calculation_processor_press", 0.0)
        .itemIn("32x #c:gems/charged_certus_quartz")
        .itemIn("16x #c:dusts/redstone")
        .itemIn("32x #c:plates/silicon")
        .itemOut("32x ae2:calculation_processor")

    event.recipes.modern_industrialization.photolithographer(64, 100)
        .itemIn("1x roll_mod:lapotron_laser", 0.0)
        .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
        .itemIn("1x ae2:logic_processor_press", 0.0)
        .itemIn("32x #c:plates/gold")
        .itemIn("16x #c:dusts/redstone")
        .itemIn("32x #c:plates/silicon")
        .itemOut("32x ae2:logic_processor")

    event.recipes.modern_industrialization.photolithographer(64, 100)
        .itemIn("1x roll_mod:lapotron_laser", 0.0)
        .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
        .itemIn("1x ae2:engineering_processor_press", 0.0)
        .itemIn("32x #c:plates/diamond")
        .itemIn("16x #c:dusts/redstone")
        .itemIn("32x #c:plates/silicon")
        .itemOut("32x ae2:engineering_processor")

    event.recipes.modern_industrialization.photolithographer(32, 200)
        .itemIn("1x roll_mod:lapotron_laser", 0.005)
        .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
        .itemIn("1x roll_mod:quartz_lamp", 0.0)
        .itemIn("2x ae2:printed_silicon")
        .itemIn("1x ae2:fluix_pearl")
        .itemIn("1x #c:wires/niobium_titanium_alloy")
        .itemOut("2x megacells:accumulation_processor")

    event.recipes.modern_industrialization.photolithographer(32, 200)
        .itemIn("1x roll_mod:lapotron_laser", 0.005)
        .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
        .itemIn("1x megacells:accumulation_processor_press", 0.0)
        .itemIn("32x ae2:printed_silicon")
        .itemIn("16x ae2:fluix_pearl")
        .itemIn("16x #c:wires/niobium_titanium_alloy")
        .itemOut("32x megacells:accumulation_processor")

    event.recipes.modern_industrialization.photolithographer(256, 400)
        .itemIn("1x roll_mod:lapotron_laser", 0.005)
        .itemIn("1x roll_mod:advanced_robot_arm", 0.005)
        .itemIn("1x roll_mod:quartz_lamp", 0.0)
        .itemIn("8x roll_mod:purple_chip_qubit")
        .itemIn("8x ae2:fluix_pearl")
        .itemIn("1x ae2:engineering_processor")
        .fluidIn("modern_industrialization:molten_glowstone", 4000)
        .itemOut("1x ae2:spatial_cell_component_2")

    event.recipes.modern_industrialization.photolithographer(256, 400)
        .itemIn("1x roll_mod:lapotron_laser", 0.005)
        .itemIn("1x roll_mod:advanced_robot_arm", 0.005)
        .itemIn("1x roll_mod:quartz_lamp", 0.0)
        .itemIn("4x roll_mod:purple_chip_accumulation")
        .itemIn("4x ae2:spatial_cell_component_2")
        .itemIn("1x ae2:engineering_processor")
        .fluidIn("modern_industrialization:molten_glowstone", 4000)
        .itemOut("1x ae2:spatial_cell_component_16")

    event.recipes.modern_industrialization.photolithographer(256, 400)
        .itemIn("1x roll_mod:lapotron_laser", 0.005)
        .itemIn("1x roll_mod:advanced_robot_arm", 0.005)
        .itemIn("1x roll_mod:quartz_lamp", 0.0)
        .itemIn("12x roll_mod:purple_chip_accumulation")
        .itemIn("4x ae2:spatial_cell_component_16")
        .itemIn("1x ae2:engineering_processor")
        .fluidIn("modern_industrialization:molten_glowstone", 4000)
        .itemOut("1x ae2:spatial_cell_component_128")

    event.recipes.modern_industrialization.photolithographer(256, 100)
        .itemIn("2x roll_mod:lapotron_laser", 0.005)
        .itemIn("4x roll_mod:advanced_robot_arm", 0.005)
        .itemIn("1x roll_mod:quartz_lamp", 0.005)
        .itemIn("1x roll_mod:fr4_sheet")
        .itemIn("1x #c:dusts/tantalum")
        .fluidIn("modern_industrialization:argon", 500)
        .itemOut("1x modern_industrialization:quantum_circuit_board")

    event.recipes.modern_industrialization.photolithographer(256, 200)
        .itemIn("2x roll_mod:lapotron_laser", 0.005)
        .itemIn("1x roll_mod:advanced_robot_arm", 0.005)
        .itemIn("1x roll_mod:quantum_star")
        .itemIn("1x roll_mod:purple_wafer")
        .itemIn("24x roll_mod:carbon_fiber")
        .itemIn("24x #c:wires/palladium")
        .itemIn("16x #c:dusts/phosphorus")
        .itemIn("16x #c:dusts/antimony")
        .fluidIn("modern_industrialization:argon", 500)
        .itemOut("1x roll_mod:purple_wafer_accumulation")

    event.recipes.modern_industrialization.photolithographer(256, 100)
        .itemIn("2x roll_mod:lapotron_laser", 0.005)
        .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
        .itemIn("1x roll_mod:quartz_lamp", 0.005)
        .itemIn("64x #c:wires/annealed_copper")
        .itemIn("4x roll_mod:engraved_crystal_chip")
        .itemIn("4x roll_mod:purple_chip_qubit")
        .itemIn("1x roll_mod:iridium_based_board_assembly")
        .itemIn("1x roll_mod:quantum_star")
        .fluidIn("modern_industrialization:argon", 500)
        .fluidIn("modern_industrialization:cryofluid", 1500)
        .itemOut("1x modern_industrialization:qubit")

    event.recipes.modern_industrialization.photolithographer(32, 200)
        .itemIn("1x roll_mod:lapotron_laser", 0.0)
        .itemIn("4x roll_mod:advanced_robot_arm", 0.005)
        .itemIn("1x roll_mod:quartz_lamp", 0.0)
        .itemIn("64x #c:wires/niobium_titanium_alloy")
        .itemIn("32x #c:wires/superconductor")
        .itemIn("4x modern_industrialization:cooling_cell")
        .itemIn("4x modern_industrialization:qubit")
        .itemIn("2x roll_mod:iridium_based_board_assembly")
        .itemIn("2x roll_mod:qubit_sensor")
        .fluidIn("500x modern_industrialization:argon")
        .itemOut("1x modern_industrialization:quantum_circuit")

    event.recipes.modern_industrialization.photolithographer(64, 300)
        .itemIn("2x roll_mod:lapotron_laser", 0.005)
        .itemIn("1x roll_mod:green_lens", 0.0)
        .itemIn("4x roll_mod:quartz_lamp", 0.005)
        .itemIn("16x roll_mod:raw_crystal_chip_parts")
        .itemIn("8x #c:wires/ruthenium")
        .itemIn("1x roll_mod:blue_chip_cpu")
        .itemIn("1x #c:plates/gold")
        .fluidIn("modern_industrialization:helium", 350)
        .fluidIn("modern_industrialization:epoxy", 50)
        .itemOut("4x roll_mod:engraved_crystal_chip")

    event.recipes.modern_industrialization.photolithographer(256, 400)
        .itemIn("1x roll_mod:lapotron_laser", 0.005)
        .itemIn("1x roll_mod:advanced_robot_arm", 0.005)
        .itemIn("1x roll_mod:quartz_lamp", 0.0)
        .itemIn("1x roll_mod:purple_wafer")
        .itemIn("32x #c:wires/annealed_copper")
        .itemIn("32x #c:wires/niobium_titanium_alloy")
        .itemIn("16x #c:prismarine_shards")
        .fluidIn("modern_industrialization:molten_glowstone", 4000)
        .fluidIn("modern_industrialization:helium", 1000)
        .itemOut("1x roll_mod:purple_wafer_qubit")
})
