ServerEvents.recipes(event => {

event.recipes.modern_industrialization.photolithographer(256, 400)
  .itemIn("1x roll_mod:lapotron_laser", 0.0)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x roll_mod:quartz_lamp", 0.0)
  .itemIn("4x modern_industrialization:titanium_64_large_plate")
  .itemIn("4x modern_industrialization:quantum_circuit")
  .itemIn("4x modern_industrialization:large_advanced_pump")
  .itemIn("2x modern_industrialization:nuclear_reactor")
  .itemIn("1x modern_industrialization:highly_advanced_machine_hull")
  .itemIn("4x roll_mod:solar_panel_11")
  .fluidIn("modern_industrialization:cryofluid", 500)
  .biome("ad_astra:is_mars")
  .itemOut("1x roll_mod:solar_panel_12")

event.recipes.modern_industrialization.photolithographer(256, 400)
  .itemIn("1x roll_mod:lapotron_laser", 0.0)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x roll_mod:quartz_lamp", 0.0)
  .itemIn("4x modern_industrialization:quantum_circuit")
  .itemIn("1x modern_industrialization:quantum_machine_hull")
  .itemIn("4x roll_mod:solar_panel_12")
  .itemIn("4x roll_mod:sunnarium_glass_mk5")
  .biome("#ad_astra:is_mars")
  .itemOut("1x roll_mod:solar_panel_13")

event.recipes.modern_industrialization.photolithographer(256, 400)
  .itemIn("1x roll_mod:lapotron_laser", 0.0)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x roll_mod:quartz_lamp", 0.0)
  .itemIn("1x modern_industrialization:quantum_machine_hull")
  .itemIn("1x modern_industrialization:singularity")
  .itemIn("4x roll_mod:solar_panel_13")
  .itemIn("4x modern_industrialization:quantum_circuit")
  .fluidIn("modern_industrialization:cryofluid", 500)
  .fluidIn("modern_industrialization:uu_matter", 1000)
  .biome("#ad_astra:is_mars")
  .itemOut("1x roll_mod:solar_panel_14")

event.recipes.modern_industrialization.photolithographer(256, 400)
  .itemIn("1x roll_mod:lapotron_laser", 0.0)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x roll_mod:quartz_lamp", 0.0)
  .itemIn("8x modern_industrialization:block_blencium_plate")
  .itemIn("4x roll_mod:solar_panel_14")
  .itemIn("1x modern_industrialization:quantum_upgrade")
  .itemIn("8x roll_mod:quantum_star")
  .itemIn("1x modern_industrialization:quantum_machine_hull")
  .itemIn("4x modern_industrialization:quantum_circuit")
  .fluidIn("modern_industrialization:cryofluid", 500)
  .fluidIn("modern_industrialization:uu_matter", 1000)
  .biome("#ad_astra:is_mercury")
  .itemOut("1x roll_mod:solar_panel_15")
    
event.recipes.modern_industrialization.photolithographer(256, 400)
    .itemIn("2x roll_mod:energium_laser", 0.005)
    .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
    .itemIn("1x roll_mod:quartz_lamp", 0.005)
    .itemIn("24x roll_mod:carbon_fiber")
    .itemIn("16x modern_industrialization:antimony_dust")
    .itemIn("2x modern_industrialization:chrome_vanadium_steel_plate")
    .itemIn("24x modern_industrialization:platinum_fine_wire")
    .itemIn("1x roll_mod:blue_wafer")
    .itemIn("16x modern_industrialization:titanium_dust")
    .biome("ad_astra:orbit")
    .itemOut("1x roll_mod:blue_wafer_ram")

event.recipes.modern_industrialization.photolithographer(256, 400)
    .itemIn("2x roll_mod:energium_laser", 0.005)
    .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
    .itemIn("1x roll_mod:quartz_lamp", 0.005)
    .itemIn("24x roll_mod:carbon_fiber")
    .itemIn("16x modern_industrialization:antimony_dust")
    .itemIn("2x modern_industrialization:chrome_vanadium_steel_plate")
    .itemIn("24x modern_industrialization:platinum_fine_wire")
    .itemIn("1x roll_mod:blue_wafer")
    .itemIn("16x modern_industrialization:titanium_dust")
    .fluidIn("modern_industrialization:argon", 1000)
    .itemOut("1x roll_mod:blue_wafer_ram")

event.recipes.modern_industrialization.photolithographer(256, 400)
  .itemIn("1x roll_mod:lapotron_laser", 0.0)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x roll_mod:quartz_lamp", 0.0)
  .itemIn("2x modern_industrialization:digital_circuit")
  .itemIn("8x roll_mod:smd_resistor")
  .itemIn("24x modern_industrialization:platinum_fine_wire")
  .itemIn("4x roll_mod:smd_transistor")
  .itemIn("4x modern_industrialization:random_access_memory")
  .itemIn("2x modern_industrialization:processing_unit_board")
  .biome("ad_astra:orbit")
  .itemOut("2x modern_industrialization:processing_unit")

event.recipes.modern_industrialization.photolithographer(256, 400)
  .itemIn("1x roll_mod:lapotron_laser", 0.0)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x roll_mod:quartz_lamp", 0.0)
  .itemIn("2x modern_industrialization:digital_circuit")
  .itemIn("8x roll_mod:smd_resistor")
  .itemIn("24x modern_industrialization:platinum_fine_wire")
  .itemIn("4x roll_mod:smd_transistor")
  .itemIn("4x modern_industrialization:random_access_memory")
  .itemIn("2x modern_industrialization:processing_unit_board")
  .fluidIn("modern_industrialization:argon", 1000)
  .itemOut("2x modern_industrialization:processing_unit")

event.recipes.modern_industrialization.photolithographer(256, 400)
  .itemIn("1x roll_mod:energium_laser", 0.0)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x roll_mod:quartz_lamp", 0.0)
  .itemIn("1x roll_mod:blue_chip_ram")
  .itemIn("3x roll_mod:smd_resistor")
  .itemIn("4x roll_mod:smd_transistor")
  .itemIn("2x roll_mod:fr4_sheet")
  .itemIn("2x modern_industrialization:electronic_circuit")
  .biome("ad_astra:orbit")
  .itemOut("4x modern_industrialization:digital_circuit")

event.recipes.modern_industrialization.photolithographer(256, 400)
  .itemIn("1x roll_mod:energium_laser", 0.0)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x roll_mod:quartz_lamp", 0.0)
  .itemIn("1x roll_mod:blue_chip_ram")
  .itemIn("3x roll_mod:smd_resistor")
  .itemIn("4x roll_mod:smd_transistor")
  .itemIn("2x roll_mod:fr4_sheet")
  .itemIn("2x modern_industrialization:electronic_circuit")
  .fluidIn("modern_industrialization:argon", 1000)
  .itemOut("4x modern_industrialization:digital_circuit")

event.recipes.modern_industrialization.photolithographer(64, 100)
  .itemIn("1x roll_mod:lapotron_laser", 0.0)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x ae2:calculation_processor_press", 0.0)
  .itemIn("32x ae2:charged_certus_quartz_crystal")
  .itemIn("16x #c:dusts/redstone")
  .itemIn("32x modern_industrialization:silicon_plate")
  .biome("ad_astra:orbit")
  .itemOut("32x ae2:calculation_processor")

event.recipes.modern_industrialization.photolithographer(64, 100)
  .itemIn("1x roll_mod:lapotron_laser", 0.0)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x ae2:calculation_processor_press", 0.0)
  .itemIn("32x ae2:charged_certus_quartz_crystal")
  .itemIn("16x #c:dusts/redstone")
  .itemIn("32x modern_industrialization:silicon_plate")
  .fluidIn("modern_industrialization:argon", 1000)
  .itemOut("32x ae2:calculation_processor")

event.recipes.modern_industrialization.photolithographer(64, 100)
  .itemIn("1x roll_mod:lapotron_laser", 0.0)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x ae2:logic_processor_press", 0.0)
  .itemIn("32x modern_industrialization:gold_plate")
  .itemIn("16x minecraft:redstone")
  .itemIn("32x modern_industrialization:silicon_plate")
  .biome("ad_astra:orbit")
  .itemOut("32x ae2:logic_processor")

event.recipes.modern_industrialization.photolithographer(64, 100)
  .itemIn("1x roll_mod:lapotron_laser", 0.0)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x ae2:logic_processor_press", 0.0)
  .itemIn("32x modern_industrialization:gold_plate")
  .itemIn("16x minecraft:redstone")
  .itemIn("32x modern_industrialization:silicon_plate")
  .fluidIn("modern_industrialization:argon", 1000)
  .itemOut("32x ae2:logic_processor")

event.recipes.modern_industrialization.photolithographer(64, 100)
  .itemIn("1x roll_mod:lapotron_laser", 0.0)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x ae2:engineering_processor_press", 0.0)
  .itemIn("32x modern_industrialization:diamond_plate")
  .itemIn("16x minecraft:redstone")
  .itemIn("32x modern_industrialization:silicon_plate")
  .biome("ad_astra:orbit")
  .itemOut("32x ae2:engineering_processor")

event.recipes.modern_industrialization.photolithographer(64, 100)
  .itemIn("1x roll_mod:lapotron_laser", 0.0)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x ae2:engineering_processor_press", 0.0)
  .itemIn("32x modern_industrialization:diamond_plate")
  .itemIn("16x minecraft:redstone")
  .itemIn("32x modern_industrialization:silicon_plate")
  .fluidIn("modern_industrialization:argon", 1000)
  .itemOut("32x ae2:engineering_processor")

event.recipes.modern_industrialization.photolithographer(32, 200)
  .itemIn("1x roll_mod:lapotron_laser", 0.005)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x roll_mod:quartz_lamp", 0.0)
  .itemIn("2x ae2:printed_silicon")
  .itemIn("1x ae2:fluix_pearl")
  .itemIn("1x modern_industrialization:niobium_titanium_alloy_fine_wire")
  .biome("ad_astra:orbit")
  .itemOut("2x megacells:accumulation_processor")

event.recipes.modern_industrialization.photolithographer(32, 200)
  .itemIn("1x roll_mod:lapotron_laser", 0.005)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x roll_mod:quartz_lamp", 0.0)
  .itemIn("2x ae2:printed_silicon")
  .itemIn("1x ae2:fluix_pearl")
  .itemIn("1x modern_industrialization:niobium_titanium_alloy_fine_wire")
  .fluidIn("modern_industrialization:argon", 1000)
  .itemOut("2x megacells:accumulation_processor")

event.recipes.modern_industrialization.photolithographer(32, 200)
  .itemIn("1x roll_mod:lapotron_laser", 0.005)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x megacells:accumulation_processor_press", 0.0)
  .itemIn("32x ae2:printed_silicon")
  .itemIn("16x ae2:fluix_pearl")
  .itemIn("16x modern_industrialization:niobium_titanium_alloy_fine_wire")
  .biome("ad_astra:orbit")
  .itemOut("32x megacells:accumulation_processor")

event.recipes.modern_industrialization.photolithographer(32, 200)
  .itemIn("1x roll_mod:lapotron_laser", 0.005)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x megacells:accumulation_processor_press", 0.0)
  .itemIn("32x ae2:printed_silicon")
  .itemIn("16x ae2:fluix_pearl")
  .itemIn("16x modern_industrialization:niobium_titanium_alloy_fine_wire")
  .fluidIn("modern_industrialization:argon", 1000)
  .itemOut("32x megacells:accumulation_processor")

event.recipes.modern_industrialization.photolithographer(256, 400)
  .itemIn("1x roll_mod:lapotron_laser", 0.005)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.005)
  .itemIn("1x roll_mod:quartz_lamp", 0.0)
  .itemIn("8x roll_mod:purple_chip_qubit")
  .itemIn("8x ae2:fluix_pearl")
  .itemIn("1x ae2:engineering_processor")
  .fluidIn("modern_industrialization:molten_glowstone", 4000)
  .biome("ad_astra:orbit")
  .itemOut("1x ae2:spatial_cell_component_2")

event.recipes.modern_industrialization.photolithographer(256, 400)
  .itemIn("1x roll_mod:lapotron_laser", 0.005)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.005)
  .itemIn("1x roll_mod:quartz_lamp", 0.0)
  .itemIn("8x roll_mod:purple_chip_qubit")
  .itemIn("8x ae2:fluix_pearl")
  .itemIn("1x ae2:engineering_processor")
  .fluidIn("modern_industrialization:molten_glowstone", 4000)
  .fluidIn("modern_industrialization:argon", 1000)
  .itemOut("1x ae2:spatial_cell_component_2")

event.recipes.modern_industrialization.photolithographer(256, 400)
  .itemIn("1x roll_mod:lapotron_laser", 0.005)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.005)
  .itemIn("1x roll_mod:quartz_lamp", 0.0)
  .itemIn("4x roll_mod:purple_chip_accumulation")
  .itemIn("4x ae2:spatial_cell_component_2")
  .itemIn("1x ae2:engineering_processor")
  .fluidIn("modern_industrialization:molten_glowstone", 4000)
  .biome("ad_astra:orbit")
  .itemOut("1x ae2:spatial_cell_component_16")

event.recipes.modern_industrialization.photolithographer(256, 400)
  .itemIn("1x roll_mod:lapotron_laser", 0.005)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.005)
  .itemIn("1x roll_mod:quartz_lamp", 0.0)
  .itemIn("4x roll_mod:purple_chip_accumulation")
  .itemIn("4x ae2:spatial_cell_component_2")
  .itemIn("1x ae2:engineering_processor")
  .fluidIn("modern_industrialization:molten_glowstone", 4000)
  .fluidIn("modern_industrialization:argon", 1000)
  .itemOut("1x ae2:spatial_cell_component_16")

event.recipes.modern_industrialization.photolithographer(256, 400)
  .itemIn("1x roll_mod:lapotron_laser", 0.005)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.005)
  .itemIn("1x roll_mod:quartz_lamp", 0.0)
  .itemIn("12x roll_mod:purple_chip_accumulation")
  .itemIn("4x ae2:spatial_cell_component_16")
  .itemIn("1x ae2:engineering_processor")
  .fluidIn("modern_industrialization:molten_glowstone", 4000)
  .biome("ad_astra:orbit")
  .itemOut("1x ae2:spatial_cell_component_128")

event.recipes.modern_industrialization.photolithographer(256, 400)
  .itemIn("1x roll_mod:lapotron_laser", 0.005)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.005)
  .itemIn("1x roll_mod:quartz_lamp", 0.0)
  .itemIn("12x roll_mod:purple_chip_accumulation")
  .itemIn("4x ae2:spatial_cell_component_16")
  .itemIn("1x ae2:engineering_processor")
  .fluidIn("modern_industrialization:molten_glowstone", 4000)
  .fluidIn("modern_industrialization:argon", 1000)
  .itemOut("1x ae2:spatial_cell_component_128")

event.recipes.modern_industrialization.photolithographer(256, 100)
  .itemIn("2x roll_mod:lapotron_laser", 0.005)
  .itemIn("4x roll_mod:advanced_robot_arm", 0.005)
  .itemIn("1x roll_mod:quartz_lamp", 0.005)
  .itemIn("1x roll_mod:fr4_sheet")
  .itemIn("1x modern_industrialization:tantalum_dust")
  .biome("ad_astra:orbit")
  .itemOut("1x modern_industrialization:quantum_circuit_board")

event.recipes.modern_industrialization.photolithographer(256, 100)
  .itemIn("2x roll_mod:lapotron_laser", 0.005)
  .itemIn("4x roll_mod:advanced_robot_arm", 0.005)
  .itemIn("1x roll_mod:quartz_lamp", 0.005)
  .itemIn("1x roll_mod:fr4_sheet")
  .itemIn("1x modern_industrialization:tantalum_dust")
  .fluidIn("modern_industrialization:argon", 500)
  .itemOut("1x modern_industrialization:quantum_circuit_board")

event.recipes.modern_industrialization.photolithographer(256, 200)
  .itemIn("2x roll_mod:lapotron_laser", 0.005)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.005)
  .itemIn("1x roll_mod:quantum_star")
  .itemIn("1x roll_mod:purple_wafer")
  .itemIn("24x roll_mod:carbon_fiber")
  .itemIn("24x modern_industrialization:palladium_fine_wire")
  .itemIn("16x modern_industrialization:phosphorus_dust")
  .itemIn("16x modern_industrialization:antimony_dust")
  .biome("ad_astra:orbit")
  .itemOut("1x roll_mod:purple_wafer_accumulation")

event.recipes.modern_industrialization.photolithographer(256, 200)
  .itemIn("2x roll_mod:lapotron_laser", 0.005)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.005)
  .itemIn("1x roll_mod:quantum_star")
  .itemIn("1x roll_mod:purple_wafer")
  .itemIn("24x roll_mod:carbon_fiber")
  .itemIn("24x modern_industrialization:palladium_fine_wire")
  .itemIn("16x modern_industrialization:phosphorus_dust")
  .itemIn("16x modern_industrialization:antimony_dust")
  .fluidIn("modern_industrialization:argon", 500)
  .itemOut("1x roll_mod:purple_wafer_accumulation")

event.recipes.modern_industrialization.photolithographer(256, 400)
  .itemIn("2x roll_mod:lapotron_laser", 0.005)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x roll_mod:quartz_lamp", 0.005)
  .itemIn("64x modern_industrialization:annealed_copper_fine_wire")
  .itemIn("4x roll_mod:engraved_crystal_chip")
  .itemIn("4x roll_mod:purple_chip_qubit")
  .itemIn("1x roll_mod:iridium_based_board_assembly")
  .itemIn("1x roll_mod:quantum_star")
  .biome("ad_astra:orbit")
  .fluidIn("modern_industrialization:cryofluid", 1500)
  .itemOut("1x modern_industrialization:qubit")

event.recipes.modern_industrialization.photolithographer(256, 400)
  .itemIn("2x roll_mod:lapotron_laser", 0.005)
  .itemIn("1x roll_mod:advanced_robot_arm", 0.0)
  .itemIn("1x roll_mod:quartz_lamp", 0.005)
  .itemIn("64x modern_industrialization:annealed_copper_fine_wire")
  .itemIn("4x roll_mod:engraved_crystal_chip")
  .itemIn("4x roll_mod:purple_chip_qubit")
  .itemIn("1x roll_mod:iridium_based_board_assembly")
  .itemIn("1x roll_mod:quantum_star")
  .fluidIn("modern_industrialization:argon", 500)
  .fluidIn("modern_industrialization:cryofluid", 1500)
  .itemOut("1x modern_industrialization:qubit")

event.recipes.modern_industrialization.photolithographer(32, 200)
  .itemIn("1x roll_mod:lapotron_laser", 0.0)
  .itemIn("4x roll_mod:advanced_robot_arm", 0.005)
  .itemIn("1x roll_mod:quartz_lamp", 0.0)
  .itemIn("64x modern_industrialization:niobium_titanium_alloy_fine_wire")
  .itemIn("32x modern_industrialization:superconductor_wire")
  .itemIn("4x modern_industrialization:cooling_cell")
  .itemIn("4x modern_industrialization:qubit")
  .itemIn("2x roll_mod:iridium_based_board_assembly")
  .itemIn("2x roll_mod:qubit_sensor")
  .biome("ad_astra:orbit")
  .itemOut("1x modern_industrialization:quantum_circuit")

event.recipes.modern_industrialization.photolithographer(32, 200)
  .itemIn("1x roll_mod:lapotron_laser", 0.0)
  .itemIn("4x roll_mod:advanced_robot_arm", 0.005)
  .itemIn("1x roll_mod:quartz_lamp", 0.0)
  .itemIn("64x modern_industrialization:niobium_titanium_alloy_fine_wire")
  .itemIn("32x modern_industrialization:superconductor_wire")
  .itemIn("4x modern_industrialization:cooling_cell")
  .itemIn("4x modern_industrialization:qubit")
  .itemIn("2x roll_mod:iridium_based_board_assembly")
  .itemIn("2x roll_mod:qubit_sensor")
  .fluidIn("500x modern_industrialization:argon")
  .itemOut("1x modern_industrialization:quantum_circuit")

event.recipes.modern_industrialization.photolithographer(64, 300)
  .itemIn("2x roll_mod:lapotron_laser", 0.005)
  .itemIn("1x roll_mod:green_lens", 0.0)
  .itemIn("4x roll_mod:quartz_lamp", 0.005)
  .itemIn("16x roll_mod:raw_crystal_chip_parts")
  .itemIn("8x modern_industrialization:ruthenium_fine_wire")
  .itemIn("1x roll_mod:blue_chip_cpu")
  .itemIn("1x modern_industrialization:gold_plate")
  .fluidIn("modern_industrialization:helium", 350)
  .fluidIn("modern_industrialization:epoxy", 50)
  .biome("ad_astra:orbit")
  .itemOut("4x roll_mod:engraved_crystal_chip")

event.recipes.modern_industrialization.photolithographer(64, 300)
  .itemIn("2x roll_mod:lapotron_laser", 0.005)
  .itemIn("1x roll_mod:green_lens", 0.0)
  .itemIn("4x roll_mod:quartz_lamp", 0.005)
  .itemIn("16x roll_mod:raw_crystal_chip_parts")
  .itemIn("8x modern_industrialization:ruthenium_fine_wire")
  .itemIn("1x roll_mod:blue_chip_cpu")
  .itemIn("1x modern_industrialization:gold_plate")
  .fluidIn("modern_industrialization:helium", 350)
  .fluidIn("modern_industrialization:epoxy", 50)
  .fluidIn("modern_industrialization:argon", 1000)
  .itemOut("4x roll_mod:engraved_crystal_chip")

event.recipes.modern_industrialization.photolithographer(256, 400)
.itemIn("1x roll_mod:lapotron_laser", 0.005)
.itemIn("1x roll_mod:advanced_robot_arm", 0.005)
.itemIn("1x roll_mod:quartz_lamp", 0.0)
.itemIn("1x roll_mod:purple_wafer")
.itemIn("32x modern_industrialization:annealed_copper_fine_wire")
.itemIn("32x modern_industrialization:niobium_titanium_alloy_fine_wire")
.itemIn("16x minecraft:prismarine_shard")
.biome("ad_astra:orbit")
.fluidIn("modern_industrialization:molten_glowstone", 4000)
.fluidIn("modern_industrialization:helium", 1000)
.itemOut("1x roll_mod:purple_wafer_qubit")

event.recipes.modern_industrialization.photolithographer(256, 400)
.itemIn("1x roll_mod:lapotron_laser", 0.005)
.itemIn("1x roll_mod:advanced_robot_arm", 0.005)
.itemIn("1x roll_mod:quartz_lamp", 0.0)
.itemIn("1x roll_mod:purple_wafer")
.itemIn("32x modern_industrialization:annealed_copper_fine_wire")
.itemIn("32x modern_industrialization:niobium_titanium_alloy_fine_wire")
.itemIn("16x minecraft:prismarine_shard")
.fluidIn("modern_industrialization:molten_glowstone", 4000)
.fluidIn("modern_industrialization:helium", 1000)
.fluidIn("modern_industrialization:argon", 1000)
.itemOut("1x roll_mod:purple_wafer_qubit")

})
